// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import PushswapController from "./pushswap_controller"
application.register("pushswap", PushswapController)

import HeroController from "./hero_controller"
application.register("hero", HeroController)

import PrintfController from "./printf_controller"
application.register("printf", PrintfController)

import SolongController from "./solong_controller"
application.register("solong", SolongController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import ScrollRevealController from "./scroll_reveal_controller"
application.register("scroll-reveal", ScrollRevealController)
